CREATE TABLE IF NOT EXISTS vehicles (
  vehicle_id VARCHAR(40) PRIMARY KEY,
  make VARCHAR(80) NOT NULL,
  model VARCHAR(80) NOT NULL,
  license_plate VARCHAR(40) NOT NULL UNIQUE,
  created_at_ms INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS drivers (
  driver_id VARCHAR(40) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  license_number VARCHAR(60) NOT NULL UNIQUE,
  contact_info VARCHAR(200) NOT NULL,
  created_at_ms INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS telemetry_events (
  event_id VARCHAR(40) PRIMARY KEY,
  driver_id VARCHAR(40) NOT NULL,
  vehicle_id VARCHAR(40) NOT NULL,
  gps_lat DOUBLE PRECISION NOT NULL,
  gps_lng DOUBLE PRECISION NOT NULL,
  speed_kph DOUBLE PRECISION NOT NULL,
  drowsy_alert BOOLEAN NOT NULL DEFAULT FALSE,
  distracted_alert BOOLEAN NOT NULL DEFAULT FALSE,
  event_ts_ms INTEGER NOT NULL
);
